### ISSUE TITLE
fix: remove term_ui dependency (breaks Elixir 1.18 compilation)

### ISSUE THREAD

**Issue by mikehostetler** [agentjido/jido_ai#161]
## Problem

`term_ui` v0.2.0 fails to compile on Elixir 1.18:

```
== Compilation error in file lib/term_ui/widgets/log_viewer.ex ==
** (ArgumentError) cannot inject attribute @level_patterns into function/macro
because cannot escape #Reference<...>
```

This breaks the `Test / Elixir 1.18` CI job. The library is not production-ready and was integrated prematurely.

## Fix

- Remove `term_ui` from `mix.exs` deps
- Remove any code that imports/uses `term_ui` modules
- Verify `mix test` and `mix quality` pass on Elixir 1.18+1.19

## Context

CI was just enabled via PR #160. This is a pre-existing issue now visible.
