### ISSUE TITLE
Compilation error on Elixir 1.18: cannot inject attribute @model_patterns into function

### ISSUE THREAD

**Issue by malcolmsgc** [agentjido/jido_ai#89]
jido_ai version 0.5.2 fails to compile on Elixir 1.18 due to an incompatibility with how module attributes containing regex patterns are used in functions.

## Environment
•  Elixir version: 1.18.4 (compiled with Erlang/OTP 25)
•  Erlang/OTP: 28 [erts-16.0]
•  jido_ai version: 0.5.2

## Error Message

```
== Compilation error in file lib/jido_ai/providers/helpers.ex ==
** (ArgumentError) cannot inject attribute @model_patterns into function/macro because cannot escape #Reference<0.436597851.1483866120.96826>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.18.4) lib/kernel.ex:3777: Kernel.do_at_escape/2
    (elixir 1.18.4) expanding macro: Kernel.@/1
    lib/jido_ai/providers/helpers.ex:43: Jido.AI.Provider.Helpers.standardize_name/1
```

Compiled regex patterns cannot be escaped and injected into functions in Elixir 1.18.

Moving @model_patterns vals into a private function is an option.

**Comment by malcolmsgc** [comment]
My bad. I see this is already in main. Sorry for the fuss.
